"""
Feature database model.

This module defines the SQLAlchemy model for discovered SAE features.
"""

from datetime import datetime
from enum import Enum

from sqlalchemy import Column, String, Float, Integer, DateTime, Text, Boolean, ForeignKey
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from ..core.database import Base


class LabelSource(str, Enum):
    """Feature label source."""
    AUTO = "auto"         # Auto-generated fallback (e.g., "feature_00123")
    USER = "user"         # User-edited label
    LLM = "llm"           # Generated by LLM (generic/deprecated)
    LOCAL_LLM = "local_llm"  # Generated by local LLM (HuggingFace models)
    OPENAI = "openai"     # Generated by OpenAI API


class Feature(Base):
    """
    Feature database model.

    Stores discovered interpretable features from trained SAE models.
    Each feature represents a learned pattern in the SAE's latent space.
    """

    __tablename__ = "features"

    # Primary identifiers
    id = Column(String(255), primary_key=True)  # Format: feat_{training_id}_{neuron_index}
    training_id = Column(
        String(255),
        ForeignKey("trainings.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    extraction_job_id = Column(
        String(255),
        ForeignKey("extraction_jobs.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    labeling_job_id = Column(
        String(255),
        ForeignKey("labeling_jobs.id", ondelete="SET NULL"),
        nullable=True,
        index=True
    )
    neuron_index = Column(Integer, nullable=False, index=True)

    # Feature identification
    name = Column(String(500), nullable=False)  # Specific interpretation (e.g., "trump_mentions")
    category = Column(String(255), nullable=True)  # High-level category (e.g., "political_terms")
    description = Column(Text, nullable=True)
    label_source = Column(String(10), nullable=False, default=LabelSource.AUTO.value)

    # Feature statistics
    activation_frequency = Column(Float, nullable=False, index=True)  # Fraction where active (>0.01)
    interpretability_score = Column(Float, nullable=False, index=True)  # 0.0-1.0
    max_activation = Column(Float, nullable=False)
    mean_activation = Column(Float, nullable=True)

    # User metadata
    is_favorite = Column(Boolean, nullable=False, default=False, index=True)
    notes = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    labeled_at = Column(DateTime(timezone=True), nullable=True)  # When feature was last labeled

    # Relationships
    training = relationship("Training", back_populates="features")
    extraction_job = relationship("ExtractionJob", back_populates="features")
    labeling_job = relationship("LabelingJob", back_populates="features")
    activations = relationship("FeatureActivation", back_populates="feature", cascade="all, delete-orphan")
    analysis_cache = relationship("FeatureAnalysisCache", back_populates="feature", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Feature(id={self.id}, name={self.name}, activation_freq={self.activation_frequency:.3f}, interpretability={self.interpretability_score:.3f})>"
