"""
Feature database model.

This module defines the SQLAlchemy model for discovered SAE features.
"""

from datetime import datetime
from enum import Enum

from sqlalchemy import BigInteger, Column, String, Float, Integer, DateTime, Text, Boolean, ForeignKey, Enum as SQLAlchemyEnum, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, ENUM as PGEnum
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from ..core.database import Base


class LabelSource(str, Enum):
    """Feature label source."""
    AUTO = "auto"         # Auto-generated fallback (e.g., "feature_00123")
    USER = "user"         # User-edited label
    LLM = "llm"           # Generated by LLM (generic/deprecated)
    LOCAL_LLM = "local_llm"  # Generated by local LLM (HuggingFace models)
    OPENAI = "openai"     # Generated by OpenAI API
    ENHANCED_LLM = "enhanced_llm"  # Generated by two-pass enhanced labeling
    MCP_AGENT = "mcp_agent"  # Written by an MCP agent (Feature 010 provenance)


class Feature(Base):
    """
    Feature database model.

    Stores discovered interpretable features from trained SAE models.
    Each feature represents a learned pattern in the SAE's latent space.
    """

    __tablename__ = "features"

    # Mirrors migration 126732716f92. See the note on FeatureAnalysisCache:
    # constraints declared only in migrations are missing from the schema the
    # unit suite builds, so the tests run against a different database.
    __table_args__ = (
        UniqueConstraint(
            "training_id", "extraction_job_id", "neuron_index",
            name="uq_features_extraction_neuron",
        ),
    )

    # Primary identifiers
    id = Column(String(255), primary_key=True)  # Format: feat_{training_id}_{neuron_index} or feat_sae_{sae_id}_{neuron_index}
    training_id = Column(
        String(255),
        ForeignKey("trainings.id", ondelete="CASCADE"),
        nullable=True,  # Nullable: either training_id OR external_sae_id must be set
        index=True
    )
    external_sae_id = Column(
        String(255),
        ForeignKey("external_saes.id", ondelete="CASCADE"),
        nullable=True,  # Nullable: either training_id OR external_sae_id must be set
        index=True
    )
    extraction_job_id = Column(
        String(255),
        ForeignKey("extraction_jobs.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    labeling_job_id = Column(
        String(255),
        ForeignKey("labeling_jobs.id", ondelete="SET NULL"),
        nullable=True,
        index=True
    )
    neuron_index = Column(Integer, nullable=False, index=True)

    # Feature identification
    name = Column(String(500), nullable=False)  # Specific interpretation (e.g., "trump_mentions")
    category = Column(String(255), nullable=True)  # High-level category (e.g., "political_terms")
    description = Column(Text, nullable=True)
    label_source = Column(
        PGEnum('auto', 'user', 'llm', 'local_llm', 'openai', 'enhanced_llm', 'mcp_agent', name='label_source_enum', create_type=False),
        nullable=False,
        default='auto'
    )

    # Feature statistics
    activation_frequency = Column(Float, nullable=False, index=True)  # Fraction where active (>0.01)

    # THE SAME QUANTITY, COUNTED BEFORE THE JUNK-TOKEN FILTER.
    #
    # `activation_frequency` above is computed from the examples extraction
    # EMITS, and emission happens after `is_junk_token` has discarded any
    # (sample, feature) pair whose peak landed on a filtered token. It therefore
    # means "fraction of samples where the peak was on a non-junk token". With
    # five of six filters on by default — and `filter_fragments` matching a
    # ~500-entry blocklist that includes ordinary words like `land`, `field` and
    # `like` — that is materially different from "fraction of samples where the
    # feature fired".
    #
    # The old column is NOT corrected in place. It feeds the dead-neuron gate
    # and the frontend's steering auto-baseline `clamp(2.9 - 2.6*freq, 1, 3)`,
    # whose constants were fitted against measured values of that very column;
    # changing its meaning would shift every auto-baseline strength in the
    # estate with nothing reporting it. Two columns, two meanings, both stated.
    #
    # NULL on every row written before this existed. That is the honest
    # encoding: those extractions did not measure it.
    activation_frequency_true = Column(Float, nullable=True, index=True)
    #: The numerator behind `activation_frequency_true`, so the denominator is
    #: auditable rather than assumed.
    activation_count_true = Column(BigInteger, nullable=True)
    interpretability_score = Column(Float, nullable=False, index=True)  # 0.0-1.0
    max_activation = Column(Float, nullable=False)
    mean_activation = Column(Float, nullable=True)

    # User metadata
    is_favorite = Column(Boolean, nullable=False, default=False, index=True)
    # star_color: null=unstarred, 'yellow'=manually starred, 'purple'=enhanced labeling in flight, 'aqua'=enhanced labeling completed
    star_color = Column(String(20), nullable=True)
    notes = Column(Text, nullable=True)

    # Quick preview of top prime tokens (populated during labeling)
    # Format: Comma-separated string of prime tokens, e.g., "▁worth, ▁worth, ▁entries, ▁brand"
    # This is purely for quick visual scanning in the UI - full examples are in FeatureActivation table
    example_tokens_summary = Column(JSONB, nullable=True)

    # NLP Analysis (pre-computed and cached for labeling)
    # Contains: token_analysis, pos_distribution, ngrams, semantic_clusters, linguistic_patterns
    nlp_analysis = Column(JSONB, nullable=True)
    nlp_processed_at = Column(DateTime(timezone=True), nullable=True)  # When NLP analysis was computed

    # ── Adjudication state ────────────────────────────────────────────────
    #
    # The OUTCOME of labeling, kept separate from `category`, which carries the
    # semantic VERDICT. Conflating them is what let 16,824 failures across the
    # estate look finished: a failure was written as a fake label
    # (category='error_feature', name='feature_{n}') with `label_source` and
    # `labeled_at` both set, so every simple "is it labeled?" test said yes.
    #
    # The distinction that matters: a judge answering "no coherent pattern"
    # (`uninterpretable`) is an ADJUDICATION and must never be redone. A judge
    # that crashed produced nothing and must always be retryable. Those are
    # `succeeded` and `failed` here; nothing else can tell them apart.
    #
    # String(20), not a PG enum, deliberately: `label_source` above is a native
    # enum and adding a value to it costs a dedicated migration, because
    # ALTER TYPE cannot run in the transaction that uses the value.
    #: server_default as well as default: the migration must fill existing
    #: rows, and create_all() in the unit suite must build the same column,
    #: or a raw INSERT passes in tests and violates NOT NULL in production.
    label_status = Column(
        String(20), nullable=False, default='pending', server_default='pending', index=True
    )
    #: Attempts spent on this feature. Caps retries so a permanently-broken
    #: feature cannot be re-queued forever by successive resumes.
    label_attempts = Column(Integer, nullable=False, default=0, server_default='0')
    #: Why the last attempt failed. Truncated to 2000 like cancellation.record_progress.
    label_error = Column(Text, nullable=True)
    label_error_at = Column(DateTime(timezone=True), nullable=True)
    #: WHICH judge produced the current verdict. sha256 over the prompt fields
    #: that change what the model sees, so "already adjudicated" means "by this
    #: same judge" — edit the template and these features become eligible again
    #: on their own. Content-addressed for the same reason LabelingTrialRun
    #: fingerprints its panel: an editable ruler silently invalidates every
    #: prior measurement.
    label_prompt_fingerprint = Column(String(64), nullable=True, index=True)
    label_model = Column(String(255), nullable=True)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    labeled_at = Column(DateTime(timezone=True), nullable=True)  # When feature was last labeled

    # Relationships
    training = relationship("Training", back_populates="features")
    external_sae = relationship("ExternalSAE", back_populates="features")
    extraction_job = relationship("ExtractionJob", back_populates="features")
    labeling_job = relationship("LabelingJob", back_populates="features")
    activations = relationship("FeatureActivation", back_populates="feature", cascade="all, delete-orphan")
    analysis_cache = relationship("FeatureAnalysisCache", back_populates="feature", cascade="all, delete-orphan")

    @property
    def source_type(self) -> str:
        """Return the source type: 'training' or 'external_sae'."""
        return "external_sae" if self.external_sae_id else "training"

    @property
    def source_id(self) -> str:
        """Return the source ID (either training_id or external_sae_id)."""
        return self.external_sae_id if self.external_sae_id else self.training_id

    def __repr__(self) -> str:
        return f"<Feature(id={self.id}, name={self.name}, activation_freq={self.activation_frequency:.3f}, interpretability={self.interpretability_score:.3f})>"
