"""add activation extractions table

Revision ID: bf3c8f1dc38c
Revises: dbcc12eb08b5
Create Date: 2025-10-14 09:41:38.203038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf3c8f1dc38c'
down_revision: Union[str, None] = 'dbcc12eb08b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_extractions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('dataset_id', sa.String(length=255), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('layer_indices', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('hook_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('max_samples', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'LOADING', 'EXTRACTING', 'SAVING', 'COMPLETED', 'FAILED', 'CANCELLED', name='extractionstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('samples_processed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_path', sa.String(length=1000), nullable=True),
    sa.Column('metadata_path', sa.String(length=1000), nullable=True),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('saved_files', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_datasets_metadata_gin'), table_name='datasets', postgresql_using='gin')
    op.alter_column('extraction_templates', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique template identifier',
               existing_nullable=False)
    op.alter_column('extraction_templates', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Template name',
               existing_nullable=False)
    op.alter_column('extraction_templates', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Template description',
               existing_nullable=True)
    op.alter_column('extraction_templates', 'layer_indices',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment=None,
               existing_comment='List of layer indices to extract from',
               existing_nullable=False)
    op.alter_column('extraction_templates', 'hook_types',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               comment=None,
               existing_comment='List of hook types (residual, mlp, attention)',
               existing_nullable=False)
    op.alter_column('extraction_templates', 'max_samples',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Maximum number of samples to process',
               existing_nullable=False)
    op.alter_column('extraction_templates', 'batch_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Batch size for processing',
               existing_nullable=False)
    op.alter_column('extraction_templates', 'top_k_examples',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of top activating examples to save',
               existing_nullable=False)
    op.alter_column('extraction_templates', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this template is marked as favorite',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('extraction_templates', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional metadata',
               existing_nullable=True)
    op.alter_column('extraction_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('extraction_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_extraction_templates_created_at'), table_name='extraction_templates')
    op.drop_index(op.f('idx_extraction_templates_extra_metadata_gin'), table_name='extraction_templates', postgresql_using='gin')
    op.drop_index(op.f('idx_extraction_templates_is_favorite'), table_name='extraction_templates')
    op.drop_index(op.f('idx_extraction_templates_name'), table_name='extraction_templates')
    op.create_index(op.f('ix_extraction_templates_created_at'), 'extraction_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_extraction_templates_is_favorite'), 'extraction_templates', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_extraction_templates_name'), 'extraction_templates', ['name'], unique=False)
    op.alter_column('models', 'quantization',
               existing_type=postgresql.ENUM('FP32', 'FP16', 'Q8', 'Q4', 'Q2', name='quantizationformat'),
               comment=None,
               existing_comment='Quantization type (FP32, FP16, INT8, INT4)',
               existing_nullable=False)
    op.alter_column('models', 'status',
               existing_type=postgresql.ENUM('DOWNLOADING', 'LOADING', 'QUANTIZING', 'READY', 'ERROR', name='modelstatus'),
               comment=None,
               existing_comment='Current processing status',
               existing_nullable=False)
    op.drop_index(op.f('idx_models_architecture'), table_name='models')
    op.drop_index(op.f('idx_models_architecture_config_gin'), table_name='models', postgresql_using='gin')
    op.drop_index(op.f('idx_models_created_at'), table_name='models')
    op.drop_index(op.f('idx_models_status'), table_name='models')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_models_status'), 'models', ['status'], unique=False)
    op.create_index(op.f('idx_models_created_at'), 'models', ['created_at'], unique=False)
    op.create_index(op.f('idx_models_architecture_config_gin'), 'models', ['architecture_config'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_models_architecture'), 'models', ['architecture'], unique=False)
    op.alter_column('models', 'status',
               existing_type=postgresql.ENUM('DOWNLOADING', 'LOADING', 'QUANTIZING', 'READY', 'ERROR', name='modelstatus'),
               comment='Current processing status',
               existing_nullable=False)
    op.alter_column('models', 'quantization',
               existing_type=postgresql.ENUM('FP32', 'FP16', 'Q8', 'Q4', 'Q2', name='quantizationformat'),
               comment='Quantization type (FP32, FP16, INT8, INT4)',
               existing_nullable=False)
    op.drop_index(op.f('ix_extraction_templates_name'), table_name='extraction_templates')
    op.drop_index(op.f('ix_extraction_templates_is_favorite'), table_name='extraction_templates')
    op.drop_index(op.f('ix_extraction_templates_created_at'), table_name='extraction_templates')
    op.create_index(op.f('idx_extraction_templates_name'), 'extraction_templates', ['name'], unique=False)
    op.create_index(op.f('idx_extraction_templates_is_favorite'), 'extraction_templates', ['is_favorite'], unique=False)
    op.create_index(op.f('idx_extraction_templates_extra_metadata_gin'), 'extraction_templates', ['extra_metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_extraction_templates_created_at'), 'extraction_templates', ['created_at'], unique=False)
    op.alter_column('extraction_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('extraction_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('extraction_templates', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional metadata',
               existing_nullable=True)
    op.alter_column('extraction_templates', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               comment='Whether this template is marked as favorite',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('extraction_templates', 'top_k_examples',
               existing_type=sa.INTEGER(),
               comment='Number of top activating examples to save',
               existing_nullable=False)
    op.alter_column('extraction_templates', 'batch_size',
               existing_type=sa.INTEGER(),
               comment='Batch size for processing',
               existing_nullable=False)
    op.alter_column('extraction_templates', 'max_samples',
               existing_type=sa.INTEGER(),
               comment='Maximum number of samples to process',
               existing_nullable=False)
    op.alter_column('extraction_templates', 'hook_types',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               comment='List of hook types (residual, mlp, attention)',
               existing_nullable=False)
    op.alter_column('extraction_templates', 'layer_indices',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment='List of layer indices to extract from',
               existing_nullable=False)
    op.alter_column('extraction_templates', 'description',
               existing_type=sa.TEXT(),
               comment='Template description',
               existing_nullable=True)
    op.alter_column('extraction_templates', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Template name',
               existing_nullable=False)
    op.alter_column('extraction_templates', 'id',
               existing_type=sa.UUID(),
               comment='Unique template identifier',
               existing_nullable=False)
    op.create_index(op.f('idx_datasets_metadata_gin'), 'datasets', ['metadata'], unique=False, postgresql_using='gin')
    op.drop_table('activation_extractions')

    # Drop the extractionstatus enum type (critical for idempotent migrations)
    sa.Enum(name='extractionstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
