"""update models table schema

Revision ID: c8c7653233ee
Revises: ed3e160eafad
Create Date: 2025-10-11 22:39:54.168492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8c7653233ee'
down_revision: Union[str, None] = 'ed3e160eafad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old indexes first
    op.drop_index(op.f('idx_models_architecture'), table_name='models')
    op.drop_index(op.f('idx_models_created_at'), table_name='models')
    op.drop_index(op.f('idx_models_metadata_gin'), table_name='models', postgresql_using='gin')
    op.drop_index(op.f('idx_models_status'), table_name='models')

    # Create new enum types
    op.execute("CREATE TYPE quantizationformat AS ENUM ('FP32', 'FP16', 'Q8', 'Q4', 'Q2')")
    op.execute("CREATE TYPE modelstatus AS ENUM ('DOWNLOADING', 'LOADING', 'QUANTIZING', 'READY', 'ERROR')")

    # Add new columns
    op.add_column('models', sa.Column('quantized_path', sa.String(length=1000), nullable=True))
    op.add_column('models', sa.Column('architecture_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('models', sa.Column('memory_required_bytes', sa.BigInteger(), nullable=True))
    op.add_column('models', sa.Column('disk_size_bytes', sa.BigInteger(), nullable=True))

    # Alter existing columns
    op.alter_column('models', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               comment=None,
               existing_comment='Unique model identifier',
               existing_nullable=False)
    op.alter_column('models', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               comment=None,
               existing_comment='Model name',
               existing_nullable=False)
    op.alter_column('models', 'architecture',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Model architecture (e.g., GPT-2, LLaMA)',
               existing_nullable=False)
    op.alter_column('models', 'params_count',
               existing_type=sa.BIGINT(),
               nullable=False,
               comment=None,
               existing_comment='Number of parameters')
    # Convert quantization column manually with USING clause
    op.execute("ALTER TABLE models ALTER COLUMN quantization TYPE quantizationformat USING quantization::quantizationformat")

    # Convert status column manually with USING clause (map old lowercase values to new uppercase values)
    op.execute("ALTER TABLE models ALTER COLUMN status TYPE modelstatus USING UPPER(status::text)::modelstatus")
    op.alter_column('models', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Download/loading progress (0-100)',
               existing_nullable=True)
    op.alter_column('models', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error message if status is ERROR',
               existing_nullable=True)
    op.alter_column('models', 'file_path',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1000),
               comment=None,
               existing_comment='Path to model files',
               existing_nullable=True)
    op.alter_column('models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    # Drop old columns
    op.drop_column('models', 'hidden_dim')
    op.drop_column('models', 'num_heads')
    op.drop_column('models', 'extra_metadata')
    op.drop_column('models', 'memory_req_bytes')
    op.drop_column('models', 'num_layers')
    # KEEP repo_id - we need it to track HuggingFace source
    # op.drop_column('models', 'repo_id')

    # Create new indexes
    op.create_index('idx_models_status', 'models', ['status'], unique=False)
    op.create_index('idx_models_architecture', 'models', ['architecture'], unique=False)
    op.create_index('idx_models_created_at', 'models', ['created_at'], unique=False)
    # GIN index for JSONB architecture_config queries
    op.create_index('idx_models_architecture_config_gin', 'models', ['architecture_config'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop new indexes
    op.drop_index('idx_models_architecture_config_gin', table_name='models', postgresql_using='gin')
    op.drop_index('idx_models_created_at', table_name='models')
    op.drop_index('idx_models_architecture', table_name='models')
    op.drop_index('idx_models_status', table_name='models')

    # Add old columns back
    op.add_column('models', sa.Column('repo_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='HuggingFace repository ID'))
    op.add_column('models', sa.Column('num_layers', sa.INTEGER(), autoincrement=False, nullable=True, comment='Number of layers'))
    op.add_column('models', sa.Column('memory_req_bytes', sa.BIGINT(), autoincrement=False, nullable=True, comment='Estimated memory requirement in bytes'))
    op.add_column('models', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Additional metadata'))
    op.add_column('models', sa.Column('num_heads', sa.INTEGER(), autoincrement=False, nullable=True, comment='Number of attention heads'))
    op.add_column('models', sa.Column('hidden_dim', sa.INTEGER(), autoincrement=False, nullable=True, comment='Hidden dimension size'))

    # Revert column changes
    op.alter_column('models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('models', 'file_path',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=512),
               comment='Path to model files',
               existing_nullable=True)
    op.alter_column('models', 'error_message',
               existing_type=sa.TEXT(),
               comment='Error message if status is ERROR',
               existing_nullable=True)
    op.alter_column('models', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Download/loading progress (0-100)',
               existing_nullable=True)
    # Convert status column back to old enum type
    op.execute("ALTER TABLE models ALTER COLUMN status TYPE model_status_enum USING LOWER(status::text)::model_status_enum")

    # Convert quantization column back to VARCHAR
    op.execute("ALTER TABLE models ALTER COLUMN quantization TYPE VARCHAR(20) USING quantization::text")
    op.alter_column('models', 'params_count',
               existing_type=sa.BIGINT(),
               nullable=True,
               comment='Number of parameters')
    op.alter_column('models', 'architecture',
               existing_type=sa.VARCHAR(length=100),
               comment='Model architecture (e.g., GPT-2, LLaMA)',
               existing_nullable=False)
    op.alter_column('models', 'name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               comment='Model name',
               existing_nullable=False)
    op.alter_column('models', 'id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               comment='Unique model identifier',
               existing_nullable=False)

    # Drop new columns
    op.drop_column('models', 'disk_size_bytes')
    op.drop_column('models', 'memory_required_bytes')
    op.drop_column('models', 'architecture_config')
    op.drop_column('models', 'quantized_path')

    # Recreate old indexes
    op.create_index('idx_models_status', 'models', ['status'], unique=False)
    op.create_index('idx_models_metadata_gin', 'models', ['extra_metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_models_created_at', 'models', ['created_at'], unique=False)
    op.create_index('idx_models_architecture', 'models', ['architecture'], unique=False)

    # Drop new enum types
    op.execute('DROP TYPE IF EXISTS modelstatus')
    op.execute('DROP TYPE IF EXISTS quantizationformat')
    # ### end Alembic commands ###
