"""create_extraction_templates_table

Revision ID: dbcc12eb08b5
Revises: abc9a08743e0
Create Date: 2025-10-13 03:04:41.057541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbcc12eb08b5'
down_revision: Union[str, None] = 'abc9a08743e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_templates',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique template identifier'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Template name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Template description'),
    sa.Column('layer_indices', postgresql.ARRAY(sa.Integer()), nullable=False, comment='List of layer indices to extract from'),
    sa.Column('hook_types', postgresql.ARRAY(sa.String(length=50)), nullable=False, comment='List of hook types (residual, mlp, attention)'),
    sa.Column('max_samples', sa.Integer(), nullable=False, comment='Maximum number of samples to process'),
    sa.Column('batch_size', sa.Integer(), nullable=False, comment='Batch size for processing'),
    sa.Column('top_k_examples', sa.Integer(), nullable=False, comment='Number of top activating examples to save'),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether this template is marked as favorite'),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_extraction_templates_created_at', 'extraction_templates', ['created_at'], unique=False)
    op.create_index('idx_extraction_templates_is_favorite', 'extraction_templates', ['is_favorite'], unique=False)
    op.create_index('idx_extraction_templates_name', 'extraction_templates', ['name'], unique=False)
    # GIN index for JSONB extra_metadata queries
    op.create_index('idx_extraction_templates_extra_metadata_gin', 'extraction_templates', ['extra_metadata'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_extraction_templates_extra_metadata_gin', table_name='extraction_templates', postgresql_using='gin')
    op.drop_index('idx_extraction_templates_name', table_name='extraction_templates')
    op.drop_index('idx_extraction_templates_is_favorite', table_name='extraction_templates')
    op.drop_index('idx_extraction_templates_created_at', table_name='extraction_templates')
    op.drop_table('extraction_templates')
    # ### end Alembic commands ###
